### ISSUE TITLE
还没上传nb商店吗，装不了啊

### ISSUE THREAD

**Issue by fllesser** [zhiyu1998/nonebot-plugin-auto-sendlike#1]

**Comment by zhiyu1998** [comment]
我勒个骚刚啊，我和 nonebot 商店对线三个星期了，我也很无奈

**Comment by fllesser** [comment]
好吧，哈哈

**Comment by fllesser** [comment]
我装上了，给个建议，点赞成功可以不用消息回应，发个这种emoji回应就好
![Image_1731911492107_edit_47617055843774.png](https://github.com/user-attachments/assets/624cb38f-55ec-468f-ade6-d050c0ffdf26)

**Comment by fllesser** [comment]
还有就是被赞的有会员的，可以点50个赞

**Comment by zhiyu1998** [comment]
> 我装上了，给个建议，点赞成功可以不用消息回应，发个这种emoji回应就好 !

感谢建议，后续添加一下
